In [1]:
import numpy as np

In [2]:
class Network:
    def __init__(self, N, alpha):
        self.alpha = alpha
        self.a1 = 0
        self.a2 = 0

        self.params = {}
        self.params['W1'] = np.random.randn(N,N+1)
        self.params['b1'] = np.zeros(N+1)
        self.params['W2'] = np.random.randn(N+1)
        self.params['b2'] = np.zeros(1)


    def sigmoid(self, x):
        return 1.0 / (1 + np.exp(-x))
    
    def sigmoid_grad(self,x):
        return (1.0 - self.sigmoid(x)) * self.sigmoid(x)
    
    def ReLU(self, x):
        return np.maximum(0,x)
    
    def tanh(self, x):
        return (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
    
    def MSELoss(self, Y_, Y):
        return 0.5 * np.sum((Y-Y_)**2)
    

    def diff(self, f, x):
        h = 1e-5
        
        grad = np.zeros_like(x)

        for i in range(x.size):
            tem_val = x[i]
            x[i] = tem_val + h
            fx1 = f(x[i],x)

            x[i] = tem_val - h
            fx2 = f(x[i],x)

            grad[i] = (fx1-fx2)/(2*h)
            x[i]=tem_val
        
        return grad
    
    def diff2(self, f, x):
        
        grad = np.zeros_like(x)

        for i,X in enumerate(x):
            grad[i] = self.diff(f,X)
        return grad


    def forward(self, x):
        self.a1 = self.sigmoid(np.dot(x,self.params['W1'])+self.params['b1'])
        self.a2 = self.sigmoid(np.dot(self.a1,self.params['W2'])+self.params['b2'])
        return self.a2
    
    def backward(self, Y,Y_):

        self.params['W2'] -= self.alpha*self.diff(self.MSELoss,self.params['W2'])

        self.params['b2'] -= self.alpha*self.diff(self.MSELoss,self.a2)

        self.params['W1'] -= self.alpha*self.diff2(self.MSELoss,self.params['W1'])
        
        self.params['b1'] -= self.alpha*self.diff(self.MSELoss,self.a1)
    
    def training(self, X, y, iters):
        for i in range(iters):
            for (x, Y_) in zip(X, y):
                Y = self.forward(x)
                if Y != Y_:
                    #error = self.MSELoss(Y_,Y)
                    #error = Y-Y_

                    self.backward(Y,Y_)
                    print(Y)
    
    def predict(self, X):
        p = self.forward(X)
        print(np.where(p>0.5,1,0), p)

In [3]:
Neuron = Network(2, 0.05)
print(Neuron.params['W1'])
print(Neuron.params['W1'].shape)
print(Neuron.params['b1'])
print(Neuron.params['W2'])
print(Neuron.params['W2'].shape)
print(Neuron.params['b1'])
print('\n\n\n')

print(Neuron.diff2(Neuron.MSELoss,Neuron.params['W1']))

[[ 0.08199843  0.36841264 -0.30008609]
 [ 0.63992549 -1.40612322 -0.15268554]]
(2, 3)
[0. 0. 0.]
[-0.42560212  0.73496182 -1.47832036]
(3,)
[0. 0. 0.]




[[ 0.0956703   0.95491295 -1.05058325]
 [ 2.83865973 -3.29948638  0.46082665]]


In [4]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [1]])
Neuron.training(X, Y, 5000)

[0.35790232]
[0.32425743]
[0.37846865]
[0.3609098]
[0.35889321]
[0.3632005]
[0.36172526]
[0.37172301]
[0.3586439]
[0.37467407]
[0.35681876]
[0.37450961]
[0.35831854]
[0.37768117]
[0.35530945]
[0.37512608]
[0.35811201]
[0.37840184]
[0.35481898]
[0.37522426]
[0.35800262]
[0.37855086]
[0.3546495]
[0.37521987]
[0.35794899]
[0.37857068]
[0.35458713]
[0.37520525]
[0.35792369]
[0.37856734]
[0.35456278]
[0.37519569]
[0.35791201]
[0.37856296]
[0.35455279]
[0.37519092]
[0.35790669]
[0.37856055]
[0.35454851]
[0.37518888]
[0.35790428]
[0.37855959]
[0.35454662]
[0.37518818]
[0.3579032]
[0.37855938]
[0.35454575]
[0.37518806]
[0.35790271]
[0.37855948]
[0.35454533]
[0.37518815]
[0.35790249]
[0.37855967]
[0.35454512]
[0.3751883]
[0.3579024]
[0.37855987]
[0.35454501]
[0.37518845]
[0.35790236]
[0.37856005]
[0.35454495]
[0.37518858]
[0.35790234]
[0.37856019]
[0.35454491]
[0.37518869]
[0.35790233]
[0.3785603]
[0.35454489]
[0.37518877]
[0.35790232]
[0.37856039]
[0.35454487]
[0.37518883]
[0.35790232]
[0.3785

In [5]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
for x in X:
    print(Neuron.predict(x))
print(Neuron.params['W1'],'\n')
print(Neuron.params['b1'],'\n')
print(Neuron.params['W2'],'\n')
print(Neuron.params['b2'],'\n')
print(Neuron.a1,'\n')

[0] [0.35790232]
None
[0] [0.37856063]
None
[0] [0.35454484]
None
[0] [0.37518901]
None
[[ 0.05010833  0.05010833  0.05010833]
 [-0.30629442 -0.30629442 -0.30629442]] 

[2.27787411e-13 2.27979461e-13 2.27832000e-13] 

[-0.38965356 -0.38965356 -0.38965356] 

[0.] 

[0.43630148 0.43630148 0.43630148] 
